WebSite/Controllers/BiletController.cs
using Business.Abstract;
using DTO.DTOEntity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebSite.Controllers
{
    [Authorize]
    public class BiletController : Controller
    {
        private readonly IBiletService _biletService;

        public BiletController(IBiletService biletService)
        {
            _biletService = biletService;
        }

        [HttpGet("Bilet/Get/{id}")]
        public IActionResult Details()
        {

            return View();
        }

        [HttpPost]
        public IActionResult AddToCart(CartDTO dto)
        {
            bool isSuccess;
            string mes;
            try
            {
                dto.UserId = Convert.ToInt32(HttpContext.User.FindFirst(x => x.Type == "Id")?.Value);

                _biletService.AddToCart(dto);
                mes = "Bilet alındı!";
                isSuccess = true;
            }
            catch (Exception ex)
            {
                mes = ex.Message;
                isSuccess = false;
            }

            return RedirectToAction("Get",
                new
                {
                    id = dto.BiletId,
                    message = mes,
                    isSuccess = isSuccess
                });
        }

    }
}

WebSite/Controllers/HomeController.cs
using Business.Abstract;
using DataAccess;
using DTO.DTOEntity;
using Microsoft.AspNetCore.Mvc;

namespace WebSite.Controllers
{
    public class HomeController : Controller
    {
        private readonly IBiletService _biletService;
        private readonly ApplicationDbContext _context;

        public HomeController(IBiletService biletService, ApplicationDbContext context)
        {
            _biletService = biletService;
            _context = context;
        }

        public IActionResult Index(int page = 1, int pageSize = 4, ProductSortOrder order = ProductSortOrder.NameAsc, string search = null)
        {
            //Search
            if (!string.IsNullOrEmpty(search))
                ViewBag.Search = search;


            //Sorting
            int allProductsCount;
            var res = _biletService.GetFilter(out allProductsCount, page, pageSize, order, search);

            ViewBag.HasPrevious = true;
            ViewBag.HasNext = true;

            if (page * pageSize >= allProductsCount)
            {
                ViewBag.HasNext = false;
            }
            if (page <= 1)
            {
                ViewBag.HasPrevious = false;
            }


            ViewBag.NameSort = order == ProductSortOrder.NameAsc ? ProductSortOrder.NameDesc : ProductSortOrder.NameAsc;
            ViewBag.PriceSort = order == ProductSortOrder.PriceAsc ? ProductSortOrder.PriceDesc : ProductSortOrder.PriceAsc;


            var pagedRs = new PagedResponseDTO<BiletDTO>(page, pageSize, res);

            ViewBag.BiletCount = _context.Bilets.Count();
            return View(pagedRs);
        }

        [HttpGet]
        public IActionResult GetCart(string message = null, bool isSuccess = true)
        {
            if (!string.IsNullOrEmpty(message))
            {
                if (isSuccess)
                    ViewBag.Success = message;
                else
                    ViewBag.Error = message;
            }

            var userId = Convert.ToInt32(HttpContext.User.FindFirst(x => x.Type == "Id")?.Value);

            var res = _biletService.GetCart(userId);

            ViewBag.CartCount = _context.Carts.Count();

            return View(res);

        }


        [HttpPost]
        public IActionResult Buy(PayDTO dto)
        {
            _biletService.Buy(dto.CartId);

            return RedirectToAction("GetCart",
                new
                {
                    message = "Sifarişiniz qəbul olundu! Qiymət " + dto.Sum + "azn",
                    isSuccess = true
                });
        }

        [HttpPost]
        public IActionResult DeleteFromCart(int cartId)
        {
            _biletService.DeleteFromCart(cartId);

            return RedirectToAction("GetCart",
                new
                {
                    message = "Sifarişiniz ləgv olundu!",
                    isSuccess = true
                });
        }

        public IActionResult Details(int id)
        {
            var values = _biletService.Get(id);
            return View(values);
        }
    }
}

WebSite/Views/Home/Details.cshtml
@model DTO.DTOEntity.BiletDTO

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_WebLayout.cshtml";
}

<section class="w3l-call-to-action_9">
    <div class="call-w3 ">
        <div class="container-fluid">
            <div class="grids">
                <div class="grids-content row text-center">

                    <div class="column display-column col-lg-6 col-md-6 col-sm-6">
                        <div class="column-five ">
                            <h3><a href="about.html" class=" ">@Model.Name</a></h3>
                            <span class="para">
                                Uçuş tarixi: @(((DateTime)Model.FlyDate).ToString("dd-MMM-yyyy"))
                                saat: @(((DateTime)Model.FlyTime).ToString("hh:mm tt"))
                            </span>
                            <br>
                            <span class="para">
                                Eniş tarixi: @(((DateTime)Model.DownDate).ToString("dd-MMM-yyyy"))
                                saat: @(((DateTime)Model.DownTime).ToString("hh:mm tt"))
                            </span>
                            <br>
                            <span class="para">Toplam mesafe: @Model.Km</span>
                            <br />
                            <span class="para">Bilet Qiyməti: @Model.Price azn</span>
                            <br>
                            @if (User.IsInRole("User"))
                            {
                                <form method="post" asp-controller="Bilet" asp-action="AddToCart">

                                    <div class="form-outline mb-4">
                                        <label>Say:  </label>
                                        <input type="number" style="width:100px" value="1" name="Count" min="1" max="10" class="form-control form-control" />
                                    </div>

                                    <button type="submit" class="btn btn-outline-success">
                                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                        Şifariş edin
                                    </button>

                                    <div class="form-outline mb-4">
                                        <input type="hidden" name="BiletId" value="@Model.Id" class="form-control form-control" />
                                    </div>

                                </form>
                            }
                        </div>

                    </div>
                    <div class="column col-lg-6 col-md-6 col-sm-6 back-three  p-0">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<partial name="~/Views/Partials/FooterHomePartial.cshtml" />

WebSite/Views/Home/GetCart.cshtml
@model IEnumerable<DTO.DTOEntity.CartDTO>

@{
    ViewData["Title"] = "GetCart";
    Layout = "~/Views/Shared/_WebLayout.cshtml";
}


<section class="w3l-recent-work-hobbies">
    <div class="recent-work ">
        <div class="container">
            <partial name="~/Views/Shared/Message.cshtml" />
            @{
                if (Model.Count() == 0)
                {
                            <div class="justify-content-center">
                                <p class="h2">Səbətiniz boşdur!</p>
                    </div>
                }
            }
            <div class="main-titles-head text-center">
                <h3 class="header-name ">
                    Sİfarİş edİlən bİletlər
                </h3>
                <p>Toplam sifarış edilən bilet sayı: @ViewBag.CartCount</p>
            </div>
            <div class="row about-about">
                @foreach (var item in Model)
                {
                    <div class="col-lg-6 col-md-6 col-sm-6 " style="margin-bottom: 20px;">
                        <div class="about-grids">
                            <h4>
                                <a asp-controller="Home" asp-action="Details" asp-route-id="@item.Id" id="head_tl">@item.BiletName</a>
                            </h4>
                            <span class="para">
                                Uçuş tarixi: @(((DateTime)item.FlyDateName).ToString("dd-MMM-yyyy"))
                                saat: @(((DateTime)item.FlyTimeName).ToString("hh:mm tt"))
                            </span>
                            <br>
                            <span class="para">
                                Eniş tarixi: @(((DateTime)item.DownDateName).ToString("dd-MMM-yyyy"))
                                saat: @(((DateTime)item.DownTimeName).ToString("hh:mm tt"))
                            </span>
                            <p class="para">Toplam mesafe: @item.BiletKm km</p>
                            <p class="para">Bilet Qiyməti: @item.BiletPrice azn</p>

                            <form method="post" asp-controller="Home" asp-action="Buy">
                                <input type="hidden" value="@item.Sum" name="Sum">
                                <input type="hidden" value="@item.Id" name="CartId">
                                <button type="submit" style="width:300px;" class="btn btn-outline-success">
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                    Al
                                </button>
                            </form>
                            <br />
                            <form method="post" asp-controller="Home" asp-action="DeleteFromCart">
                                <input type="hidden" name="cartId" value="@item.Id">
                                <button type="submit" style="width:300px;" class="btn btn-outline-danger">
                                    <i class="fa fa-trash" aria-hidden="true"></i>
                                    Sil
                                </button>
                            </form>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>

</section>
<partial name="~/Views/Partials/FooterHomePartial.cshtml" />

WebSite/Views/Home/Index.cshtml
@using DTO.DTOEntity
@model PagedResponseDTO<BiletDTO>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_WebLayout.cshtml";
}


<script src="~/WebSale/assets/js/jquery-3.3.1.min.js"></script>
<!-- Common jquery plugin -->
<!--bootstrap working-->
<script src="~/WebSale/assets/js/bootstrap.min.js"></script>
<!-- //bootstrap working-->
<!-- disable body scroll which navbar is in active -->
<script>
    $(function () {
        $('.navbar-toggler').click(function () {
            $('body').toggleClass('noscroll');
        })
    });
</script>


<section class="w3l-recent-work-hobbies">
    <div class="recent-work ">
        <div class="container">
            <div class="main-titles-head text-center">
                <h3 class="header-name ">
                    Satışda olan bİletlər
                </h3>
                <p>Toplam aktiv satışda olan bilet sayı: @ViewBag.BiletCount</p>
            </div>
            <div class="row justify-content-md-center mt-3">
                <div class="col col-md-auto">
                    <ul class="list-group bg-white list-group-horizontal">
                        <li class="list-group-item list-group-item-secondary">
                            <a class="text-decoration-none" asp-action="Index" asp-route-order="@ViewBag.NameSort" asp-route-search="@ViewBag.Search">Ada görə</a>
                        </li>
                        <li class="list-group-item list-group-item-secondary">
                            <a class="text-decoration-none" asp-action="Index" asp-route-order="@ViewBag.PriceSort" asp-route-search="@ViewBag.Search">Qiymətə görə</a>
                        </li>
                    </ul>
                </div>
            </div>
            <br />
            <br />
            <div class="row about-about">
                @foreach (var item in Model.Values)
                {
                    <div class="col-lg-6 col-md-6 col-sm-6 " style="margin-bottom: 20px;">
                        <div class="about-grids">
                            <h4>
                                <a asp-controller="Home" asp-action="Details" asp-route-id="@item.Id" id="head_tl">@item.Name</a>
                            </h4>
                            <span class="para">
                                Uçuş tarixi: @(((DateTime)item.FlyDate).ToString("dd-MMM-yyyy"))
                                saat: @(((DateTime)item.FlyTime).ToString("hh:mm tt"))
                            </span>
                            <br>
                            <span class="para">
                                Eniş tarixi: @(((DateTime)item.DownDate).ToString("dd-MMM-yyyy"))
                                saat: @(((DateTime)item.DownTime).ToString("hh:mm tt"))
                            </span>
                            <p class="para">Toplam mesafe: @item.Km km</p>
                            <p class="para">Bilet Qiyməti: @item.Price azn</p>
                            <br>
                            <a asp-controller="Home" asp-action="Details" asp-route-id="@item.Id"
                           class="btn btn-primary">Şifariş edin</a>
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="row justify-content-md-center">

            <ul class="pagination justify-content-center">
                @if (ViewBag.HasPrevious)
                {
                    <li class="page-item">
                        <a class="page-link" asp-action="Index" asp-route-page="@(Model.Page-1)"
                       asp-route-order="@ViewBag.PriceSort" asp-route-search="@ViewBag.Search">Previous</a>
                    </li>
                }
                else
                {
                    <li class="page-item disabled"><a class="page-link">Previous</a></li>
                }
                @if (ViewBag.HasNext)
                {
                    <li class="page-item">
                        <a class="page-link" asp-action="Index" asp-route-page="@(Model.Page+1)"
                       asp-route-order="@ViewBag.PriceSort" asp-route-search="@ViewBag.Search">Next</a>
                    </li>
                }
                else
                {
                    <li class="page-item disabled"><a class="page-link">Next</a></li>
                }
            </ul>
        </div>
    </div>

</section>
<partial name="~/Views/Partials/FooterHomePartial.cshtml" />